FROM node:16.13.1-alpine as build
WORKDIR /app
COPY package.json .
COPY package-lock.json .
RUN npm install
COPY . .
RUN npm run build

FROM nginx:1.20-alpine
COPY --from=build /app/build /usr/share/nginx/html 